kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alibaba-disk-csi-snapshotter-binding
subjects:
  - kind: ServiceAccount
    name: alibaba-disk-csi-driver-controller-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: alibaba-disk-external-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
