apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: alibaba-disk-csi-driver-trusted-ca-bundle
  namespace: openshift-cluster-csi-drivers
