apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-disk-efficiency
provisioner: diskplugin.csi.alibabacloud.com
parameters:
  type: cloud_efficiency
reclaimPolicy: Delete
allowVolumeExpansion: true